// <auto-generated />
using System;
using Domain.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.ListOfCalculations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BakrCredit")
                        .HasColumnType("float");

                    b.Property<double>("BakrDebit")
                        .HasColumnType("float");

                    b.Property<double>("BakrPortion")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ListDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MainTableId")
                        .HasColumnType("int");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<double>("YomeCredit")
                        .HasColumnType("float");

                    b.Property<double>("YomeDebit")
                        .HasColumnType("float");

                    b.Property<double>("YomePortion")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MainTableId");

                    b.ToTable("ListOfCalculations");
                });

            modelBuilder.Entity("Domain.Entities.MainTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainTable");
                });

            modelBuilder.Entity("Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.ListOfCalculations", b =>
                {
                    b.HasOne("Domain.Entities.MainTable", null)
                        .WithMany("ListOfCalculations")
                        .HasForeignKey("MainTableId");
                });
#pragma warning restore 612, 618
        }
    }
}
